# Generated by Django 4.2.3 on 2023-08-01 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('Title', models.CharField(max_length=180)),
                ('Year', models.CharField(max_length=180)),
                ('Rated', models.CharField(max_length=5)),
                ('Released', models.CharField(max_length=30)),
                ('Runtime', models.CharField(max_length=30)),
                ('Genre', models.CharField(max_length=50)),
                ('Director', models.CharField(max_length=100)),
                ('Writer', models.CharField(max_length=100)),
                ('Actors', models.CharField(max_length=300)),
                ('Plot', models.CharField(max_length=500)),
                ('Language', models.CharField(max_length=50)),
                ('Country', models.CharField(max_length=180)),
                ('Awards', models.CharField(max_length=180)),
                ('Poster', models.CharField(max_length=500)),
                ('Metascore', models.CharField(max_length=10)),
                ('imdbRating', models.CharField(max_length=10)),
                ('imdbVotes', models.CharField(max_length=10)),
                ('imdbID', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=10)),
                ('DVD', models.CharField(max_length=30)),
                ('BoxOffice', models.CharField(max_length=30)),
                ('Production', models.CharField(blank=True, max_length=30, null=True)),
                ('Website', models.CharField(blank=True, max_length=30, null=True)),
                ('Response', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Source', models.CharField(max_length=30)),
                ('Value', models.CharField(max_length=30)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='api.movie')),
            ],
        ),
    ]
