# Generated by Django 4.2.3 on 2024-04-20 21:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('Title', models.CharField(max_length=180)),
                ('Year', models.CharField(max_length=180)),
                ('Rated', models.CharField(max_length=25)),
                ('Released', models.CharField(max_length=30)),
                ('Runtime', models.CharField(max_length=30)),
                ('Genre', models.CharField(max_length=50)),
                ('Director', models.CharField(max_length=100)),
                ('Writer', models.CharField(max_length=100)),
                ('Actors', models.CharField(max_length=300)),
                ('Plot', models.CharField(max_length=500)),
                ('Language', models.CharField(max_length=50)),
                ('Country', models.CharField(max_length=180)),
                ('Awards', models.CharField(max_length=180)),
                ('Poster', models.CharField(max_length=500)),
                ('Metascore', models.CharField(max_length=10)),
                ('imdbRating', models.CharField(max_length=10)),
                ('imdbVotes', models.CharField(max_length=10)),
                ('imdbID', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('Type', models.CharField(max_length=10)),
                ('DVD', models.CharField(max_length=30)),
                ('BoxOffice', models.CharField(max_length=30)),
                ('Production', models.CharField(blank=True, max_length=30, null=True)),
                ('Website', models.CharField(blank=True, max_length=30, null=True)),
                ('Response', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('permalink', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='UserQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserMovie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Source', models.CharField(max_length=30)),
                ('Value', models.CharField(max_length=30)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='api.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Question', models.CharField(max_length=30)),
                ('Answer1', models.CharField(max_length=100)),
                ('Answer2', models.CharField(max_length=100)),
                ('Answer3', models.CharField(max_length=100)),
                ('Answer4', models.CharField(max_length=100)),
                ('Answer5', models.CharField(max_length=100)),
                ('CorrectAnswer1', models.CharField(max_length=100)),
                ('CorrectAnswer2', models.CharField(max_length=100)),
                ('CorrectAnswer3', models.CharField(max_length=100)),
                ('CorrectAnswer4', models.CharField(max_length=100)),
                ('CorrectAnswer5', models.CharField(max_length=100)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.quiz')),
            ],
        ),
    ]
