# Generated by Django 4.2.3 on 2023-08-21 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Response',
            field=models.CharField(max_length=30),
        ),
    ]
