# Generated by Django 4.2.3 on 2024-04-21 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='Answer1',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='question',
            name='Answer2',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='question',
            name='Answer3',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='question',
            name='Answer4',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='question',
            name='Answer5',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='question',
            name='CorrectAnswer1',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='question',
            name='CorrectAnswer2',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='question',
            name='CorrectAnswer3',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='question',
            name='CorrectAnswer4',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='question',
            name='CorrectAnswer5',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='permalink',
            field=models.CharField(max_length=64),
        ),
    ]
