# Generated by Django 4.2.3 on 2024-04-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_quiz_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='CorrectAnswer5',
            field=models.CharField(max_length=128),
        ),
    ]
