# Generated by Django 4.2.3 on 2023-08-23 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_user_id_usermovie_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='Rated',
            field=models.CharField(max_length=25),
        ),
    ]
